FROM node:16-alpine3.11 as builder

COPY package.json yarn.lock /app/
COPY src/server/prisma/schema.prisma /app/src/server/prisma/schema.prisma

WORKDIR /app

RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn yarn --frozen-lockfile

FROM node:16-alpine3.11

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY . /app

EXPOSE 5555

CMD ["yarn", "prisma", "studio"]
